# Generated by Django 4.2.5 on 2023-09-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.ManyToManyField(to='books.generolivro'),
        ),
    ]
