# Generated by Django 4.2.5 on 2023-09-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='usuario',
        ),
    ]
