# Generated by Django 4.2.5 on 2023-09-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_livro_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='venderOuEmprestar',
            new_name='vender',
        ),
    ]
