# Generated by Django 4.2.5 on 2023-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_venderouemprestar_livro_vender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='preço',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='vender',
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo_transacao',
            field=models.CharField(choices=[('venda', 'Venda'), ('troca', 'Troca'), ('doacao', 'Doação')], default='doacao', max_length=10),
        ),
    ]
