# Generated by Django 4.2.5 on 2023-09-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='usuario_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
