# Generated by Django 4.2.5 on 2023-10-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_livro_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='disponivel',
        ),
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
