# Generated by Django 4.2.5 on 2023-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_livro_disponivel_alter_livro_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
