# Generated by Django 4.2.5 on 2023-10-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_livro_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='DDD+Numero', max_length=20, null=True),
        ),
    ]
