# Generated by Django 4.2.5 on 2023-10-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_livro_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/capas/'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='DDD + Número', max_length=20, null=True),
        ),
    ]
