# Generated by Django 4.2.5 on 2023-10-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_livro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_exclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
