# Generated by Django 4.2.5 on 2023-10-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_rename_sinopse_feedbacks_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='mensagem',
            field=models.TextField(),
        ),
    ]
